# Generated by Django 6.0.2 on 2026-02-24 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newappvarity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newappvarity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
